(ns breddit.data)

(def book-codes [
  "GEN",  "EXO",  "LEV",  "NUM",  "DEU",  "JOS",  "JDG",  "RUT",  "1SA",  "2SA",
  "1KI",  "2KI",  "1CH",  "2CH",  "EZR",  "NEH",  "EST",  "JOB",  "PSA",  "PRO",
  "ECC",  "SNG",  "ISA",  "JER",  "LAM",  "EZK",  "DAN",  "HOS",  "JOL",  "AMO",
  "OBA",  "JON",  "MIC",  "NAM",  "HAB",  "ZEP",  "HAG",  "ZEC",  "MAL",  "MAT",
  "MRK",  "LUK",  "JHN",  "ACT",  "ROM",  "1CO",  "2CO",  "GAL",  "EPH",  "PHP",
  "COL",  "1TH",  "2TH",  "1TI",  "2TI",  "TIT",  "PHM",  "HEB",  "JAS",
  "1PE",  "2PE",  "1JN",  "2JN",  "3JN",  "JUD",  "REV"])

(def book-list [
  {:num  1, :chapters 0, :verses 0, :code "GEN", :nl "Genesis"            },           
  {:num  2, :chapters 0, :verses 0, :code "EXO", :nl "Exodus"             },            
  {:num  3, :chapters 0, :verses 0, :code "LEV", :nl "Leviticus"          },         
  {:num  4, :chapters 0, :verses 0, :code "NUM", :nl "Numeri"             },            
  {:num  5, :chapters 0, :verses 0, :code "DEU", :nl "Deuteronomium"      },     
  {:num  6, :chapters 0, :verses 0, :code "JOS", :nl "Jozua"              },             
  {:num  7, :chapters 0, :verses 0, :code "JDG", :nl "Richteren"          },         
  {:num  8, :chapters 0, :verses 0, :code "RUT", :nl "Ruth"               },              
  {:num  9, :chapters 0, :verses 0, :code "1SA", :nl "1 Samuel"           },          
  {:num 10, :chapters 0, :verses 0, :code "2SA", :nl "2 Samuel"           },          
  {:num 11, :chapters 0, :verses 0, :code "1KI", :nl "1 Koningen"         },        
  {:num 12, :chapters 0, :verses 0, :code "2KI", :nl "2 Koningen"         },        
  {:num 13, :chapters 0, :verses 0, :code "1CH", :nl "1 Kronieken"        },       
  {:num 14, :chapters 0, :verses 0, :code "2CH", :nl "2 Kronieken"        },       
  {:num 15, :chapters 0, :verses 0, :code "EZR", :nl "Ezra"               },              
  {:num 16, :chapters 0, :verses 0, :code "NEH", :nl "Nehemia"            },           
  {:num 17, :chapters 0, :verses 0, :code "EST", :nl "Esther"             },            
  {:num 18, :chapters 0, :verses 0, :code "JOB", :nl "Job"                },               
  {:num 19, :chapters 0, :verses 0, :code "PSA", :nl "Psalmen"            },           
  {:num 20, :chapters 0, :verses 0, :code "PRO", :nl "Spreuken"           },          
  {:num 21, :chapters 0, :verses 0, :code "ECC", :nl "Prediker"           },          
  {:num 22, :chapters 0, :verses 0, :code "SNG", :nl "Hooglied"           },          
  {:num 23, :chapters 0, :verses 0, :code "ISA", :nl "Jesaja"             },            
  {:num 24, :chapters 0, :verses 0, :code "JER", :nl "Jeremia"            },           
  {:num 25, :chapters 0, :verses 0, :code "LAM", :nl "Klaagliederen"      },     
  {:num 26, :chapters 0, :verses 0, :code "EZK", :nl "Ezechiël"           },          
  {:num 27, :chapters 0, :verses 0, :code "DAN", :nl "Daniël"             },            
  {:num 28, :chapters 0, :verses 0, :code "HOS", :nl "Hosea"              },             
  {:num 29, :chapters 0, :verses 0, :code "JOL", :nl "Joël"               },              
  {:num 30, :chapters 0, :verses 0, :code "AMO", :nl "Amos"               },              
  {:num 31, :chapters 0, :verses 0, :code "OBA", :nl "Obadja"             },            
  {:num 32, :chapters 0, :verses 0, :code "JON", :nl "Jona"               },              
  {:num 33, :chapters 0, :verses 0, :code "MIC", :nl "Micha"              },             
  {:num 34, :chapters 0, :verses 0, :code "NAM", :nl "Nahum"              },             
  {:num 35, :chapters 0, :verses 0, :code "HAB", :nl "Habakuk"            },           
  {:num 36, :chapters 0, :verses 0, :code "ZEP", :nl "Zefanja"            },           
  {:num 37, :chapters 0, :verses 0, :code "HAG", :nl "Haggaï"             },            
  {:num 38, :chapters 0, :verses 0, :code "ZEC", :nl "Zacharia"           },          
  {:num 39, :chapters 0, :verses 0, :code "MAL", :nl "Maleachi"           },          
  {:num 40, :chapters 0, :verses 0, :code "MAT", :nl "Mattheüs"           },          
  {:num 41, :chapters 0, :verses 0, :code "MRK", :nl "Markus"             },            
  {:num 42, :chapters 0, :verses 0, :code "LUK", :nl "Lukas"              },             
  {:num 43, :chapters 0, :verses 0, :code "JHN", :nl "Johannes"           },          
  {:num 44, :chapters 0, :verses 0, :code "ACT", :nl "Handelingen"        },       
  {:num 45, :chapters 0, :verses 0, :code "ROM", :nl "Romeinen"           },          
  {:num 46, :chapters 0, :verses 0, :code "1CO", :nl "1 Korinthe"         },        
  {:num 47, :chapters 0, :verses 0, :code "2CO", :nl "2 Korinthe"         },        
  {:num 48, :chapters 0, :verses 0, :code "GAL", :nl "Galaten"            },           
  {:num 49, :chapters 0, :verses 0, :code "EPH", :nl "Efeze"              },             
  {:num 50, :chapters 0, :verses 0, :code "PHP", :nl "Filippenzen"        },       
  {:num 51, :chapters 0, :verses 0, :code "COL", :nl "Kolossenzen"        },       
  {:num 52, :chapters 0, :verses 0, :code "1TH", :nl "1 Thessalonicenzen" },
  {:num 53, :chapters 0, :verses 0, :code "2TH", :nl "2 Thessalonicenzen" },
  {:num 54, :chapters 0, :verses 0, :code "1TI", :nl "1 Timotheüs"        },       
  {:num 55, :chapters 0, :verses 0, :code "2TI", :nl "2 Timotheüs"        },       
  {:num 56, :chapters 0, :verses 0, :code "TIT", :nl "Titus"              },             
  {:num 57, :chapters 0, :verses 0, :code "PHM", :nl "Filemon"            },           
  {:num 58, :chapters 0, :verses 0, :code "HEB", :nl "Hebreeën"           },          
  {:num 59, :chapters 0, :verses 0, :code "JAS", :nl "Jakobus"            },           
  {:num 60, :chapters 0, :verses 0, :code "1PE", :nl "1 Petrus"           },          
  {:num 61, :chapters 0, :verses 0, :code "2PE", :nl "2 Petrus"           },          
  {:num 62, :chapters 0, :verses 0, :code "1JN", :nl "1 Johannes"         },        
  {:num 63, :chapters 0, :verses 0, :code "2JN", :nl "2 Johannes"         },        
  {:num 64, :chapters 0, :verses 0, :code "3JN", :nl "3 Johannes"         },        
  {:num 65, :chapters 0, :verses 0, :code "JUD", :nl "Judas"              },             
  {:num 66, :chapters 0, :verses 0, :code "REV", :nl "Openbaring"         }
])

(def book-code->data
  (reduce conj {} (map-indexed #(vector %2 (book-list %1)) book-codes)))